FROM jenkins/jnlp-slave

USER root

RUN mkdir -p /etc/ansible && chmod 755 /etc/ansible

COPY ansible.cfg /etc/ansible/ansible.cfg 

RUN apt-get update 

RUN DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y -q curl apt-transport-https gnupg-agent software-properties-common build-essential ca-certificates git

RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

RUN apt-get update

RUN apt-get -y install docker-ce

RUN docker -v /var/run/docker.sock:/var/run/docker.sock

RUN apt-get update && apt-get install python3-pip build-essential libssl-dev libffi-dev python-dev python3-venv sshpass -y && apt-get clean

RUN curl -s https://storage.googleapis.com/golang/go1.10.1.linux-amd64.tar.gz| tar -v -C /usr/local -xz

ENV GOPATH /go
ENV GOROOT /usr/local/go
ENV PATH $PATH:/usr/local/go/bin

RUN pip3 install ansible

USER jenkins

ENTRYPOINT ["jenkins-slave"]